### ISSUE TITLE
Stolpi

### ISSUE THREAD

**Issue by KapusN13** [matijapretnar/programiranje-1#6]
V datoteki dinamicno.py (programiranje-1/12-dinamicno-programiranje/predavanja/dinamicno.py), se program stolpi(n) "zacikla". Za robni pogoj ni dovolj dati n == 0 ker ga v nekaterih primerih preskoči in gre v negativna števila. Sam sem robne primere spremenil v 
    if n == 0:
        return 1
    elif n < 0:
        return 0
in program deluje pravilno.

**Comment by matijapretnar** [comment]
Ali lahko odprete kar pull request s popravkom?
